version: '3.8'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: ".env"
    networks:
      - stack
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=calendso

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL=http://localhost:4000
        NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
        NEXT_PUBLIC_LICENSE_CONSENT=agree
        CALCOM_TELEMETRY_DISABLED=1
        NEXTAUTH_SECRET=secret
        CALENDSO_ENCRYPTION_KEY=secret
        DATABASE_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
        DATABASE_DIRECT_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
    restart: always
    networks:
      - stack
    ports:
      - 4000:3000
    env_file: ".env"
    environment:
      - DATABASE_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
      - DATABASE_DIRECT_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
      - NEXT_PUBLIC_WEBAPP_URL=http://localhost:4000
      - NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - CALCOM_TELEMETRY_DISABLED=1
      - NEXTAUTH_SECRET=secret
      - CALENDSO_ENCRYPTION_KEY=secret
    depends_on:
      - database

  studio:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - stack
    ports:
      - 5555:5555
    env_file: ".env"
    environment:
      - DATABASE_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
      - DATABASE_DIRECT_URL=postgresql://unicorn_user:magical_password@database:5432/calendso
      - NEXT_PUBLIC_WEBAPP_URL=http://localhost:4000
      - NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
      - NEXTAUTH_SECRET=secret
    depends_on:
      - database
    command:
      - npx
      - prisma
      - studio
